Atualizando políticas de contribuição e template de PR
fga-eps-mds/2023-2-GEROcuidado-APIUsuario pull request #21
Opened 2023-11-22 01:40 UTC by EduardoGurgel

## Descrição

Atualizando o template de Pull Request e adicionando as políticas de contribuição.

## Tipos de Mudanças
 - [x] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [ ] Documentação
 - [ ] Experiência do usuário (UX)
 - [ ] Melhoria de desempenho

2023-11-22 10:25 UTC, pedro-cella reviewed
Ainda não posso aprovar devido a uma revisão necessária nos documentos

2023-11-22 10:27 UTC, pedro-cella requested changes
No caso creio que apenas os template de PR seja mais significativo, visto que as issues são somente criadas no repositório de DOC.

2023-11-22 15:59 UTC, EduardoGurgel commented
Certo, removi o template de issues

2023-11-23 10:31 UTC, pedro-cella approved these changes

2023-11-23 11:19 UTC, merged